### PR TITLE
FT: Dockerize server and adds support for hot reload

### PR DESCRIPTION
**Pull request by RuiSanches**
- Creates multistage dockerfile (dev and prod)
- Adds support for denon (hot reload) on local dev host and inside development docker stage
- Adds example commands to execute for development and production docker stages

### CODE REVIEW

**Comment by RuiSanches** [comment]
Comment Test 1

**Comment by RuiSanches** [comment]
Comment Test 3

**Comment by RuiSanches** [comment]
Test Comment 4

**Comment by RuiSanches** [comment]
Test Comment 5

**Comment by RuiSanches** [comment]
Test Comment 6

**Comment by RuiSanches** [comment]
Test Comment 7

**Comment by RuiSanches** [comment]
Test Comment 8

**Comment by RuiSanches** [comment]
Test Comment 9

**Comment by RuiSanches** [comment]
Test Comment 10

**Comment by RuiSanches** [comment]
Test Comment 11

**Comment by RuiSanches** [comment]
Test Comment 12

**Comment by RuiSanches** [comment]
Test Comment 13

**Comment by RuiSanches** [comment]
Test Comment 14

**Review by Pedro-Sanches — APPROVED** [review]

**Pull request merged**
